Update git submodules
* Update docs/submodules/functest from branch 'master'
  - Revert "Temporarily disable HOT including OS::Nova::FloatingIPAssociation"
    
    This reverts commit 59ba5abb31018282bca796ee0c0652d61192c6bf.
    
    Change-Id: I87a01b828668123dc9d96f5ac7823686ff0fb10e
    Signed-off-by: Cédric Ollivier <cedric.ollivier@orange.com>
    
  - Add secrets operations in cloudify.py
    
    It tries to prevent race conditions when running cloudify_ims.
    
    Traceback (most recent call last):
      File "/usr/lib/python2.7/site-packages/functest/core/singlevm.py", line 411, in run
        if not self.execute():
      File "/usr/lib/python2.7/site-packages/functest/opnfv_tests/vnf/ims/cloudify_ims.py", line 120, in execute
        self.cfy_client.secrets.create(k, val)
      File "/usr/lib/python2.7/site-packages/cloudify_rest_client/secrets.py", line 86, in create
        response = self.api.put('/secrets/{0}'.format(key), data=data)
      File "/usr/lib/python2.7/site-packages/cloudify_rest_client/client.py", line 263, in put
        timeout=timeout)
      File "/usr/lib/python2.7/site-packages/cloudify_rest_client/client.py", line 233, in do_request
        'SSL, but the client does'.format(e)
    ConnectionError: ('Connection aborted.', BadStatusLine("''",))
    
    Change-Id: Id2603bbda462b50d3140b6f45894c8810d542e4c
    Signed-off-by: Cédric Ollivier <cedric.ollivier@orange.com>
    
  - Add helper to find string in console
    
    It allows checking when cloud-init is finished (see heat_ims).
    
    Change-Id: I951aabff29457d7b7544a809f9fce1f83706035e
    Signed-off-by: Cédric Ollivier <cedric.ollivier@orange.com>