Update git submodules
* Update docs/submodules/parser from branch 'master'
  - Merge "Fix functest_run script for role of heat_stack_owner"
  - Fix functest_run script for role of heat_stack_owner
    
    When update openstack to ocata and run test in functest, the following
    error happends:
      ERROR: Missing required credential: roles ['heat_stack_owner']
    It need to add role heat_stack_owner to parser user
    
    JIRA: PARSER-156
    
    Change-Id: Ie0417c53c7dbd28efe8d9c4eb3fda23de8e1f841
    Signed-off-by: shangxdy <shang.xiaodong@zte.com.cn>