Update git submodules
* Update docs/submodules/dovetail from branch 'master'
  - Bugfix: it crashes when check_tc_result returns None
    
    The function 'check_tc_result' may return 'None'.
    In this case it will throw an exception because of
    https://github.com/opnfv/dovetail/blob/master/dovetail/run.py#L65
    
    The exception is like
    Traceback (most recent call last):
    File "/usr/local/lib/python2.7/dist-packages/dovetail/run.py", line 339, in <module>
    main()
    File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 716, in _call_
    return self.main(*args, **kwargs)
    File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
    File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
    File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
    File "/usr/local/lib/python2.7/dist-packages/dovetail/run.py", line 304, in main
    duration = run_test(testsuite_yaml, testarea, logger, kwargs)
    File "/usr/local/lib/python2.7/dist-packages/dovetail/run.py", line 65, in run_test
    if stop_on_fail['criteria'] == "FAIL" and kwargs['stop']:
    TypeError: 'NoneType' object has no attribute '_getitem_'
    
    JIRA: DOVETAIL-622
    
    Change-Id: I9e612b380c3dfb148692074a3bf8eb31875213ac
    Signed-off-by: xudan <xudan16@huawei.com>