Update git submodules
* Update docs/submodules/fuel from branch 'master'
  - Merge "[baremetal] Retry cinder.controller on failure"
  - [baremetal] Retry cinder.controller on failure
    
    Occasionally, cinderng.volume_type_present errors with:
    ClientException: Service Unavailable (HTTP 503)
    Instead of retrying the whole state file, use `wait_for` macro
    to retry only this high state up to 5 times.
    
    Change-Id: Ib9ef017aca737e53c853007c13107d56d856c016
    Signed-off-by: Alexandru Avadanii <Alexandru.Avadanii@enea.com>