Update git submodules
* Update docs/submodules/yardstick from branch 'master'
  - Merge "Bugfix: AttributeError when run tc055"
  - Bugfix: AttributeError when run tc055
    
    JIRA: YARDSTICK-662
    
    When I run tc055, I got an error, see log:
    Traceback (most recent call last):
          File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in
          _bootstrap
              self.run()
            File "/usr/lib/python2.7/multiprocessing/process.py", line 114,
            in run
              self._target(*self._args, **self._kwargs)
            File
          "/usr/local/lib/python2.7/dist-packages/yardstick/benchmark/runners/iteration.py",
          line 46, in _worker_process
              initial_rate = options_cfg.get("rate", 100)
          AttributeError: 'NoneType' object has no attribute 'get'
    
    This is because in the former patch, we get 'options' by scenario_cfg['options'], it is
    unsafe since some test case do not have 'options' field. For tc055, 'options' is None.
    
    Change-Id: I18a4a7954c18c609f422da403fe65c4739c93648
    Signed-off-by: chenjiankun <chenjiankun1@huawei.com>