Update git submodules
* Update docs/submodules/releng from branch 'master'
  - Merge "Bugfix: Error when create pod.yaml file if one node's role is None"
  - Bugfix: Error when create pod.yaml file if one node's role is None
    
    DOVETAIL-426
    
    Error message:
    if node.roles[0].lower() == "controller":
    IndexError: list index out of range
    
    Change-Id: I96d26cc3798b993b5b296f554becfc175e3e87b4
    Signed-off-by: xudan <xudan16@huawei.com>