Update git submodules
* Update docs/submodules/dovetail from branch 'master'
  - Bugfix: Build docker image failed because of lacking of packages
    
    JIRA: DOVETAIL-475
    
    1. Dovetail fails to build Docker image.
       CI Link: https://build.opnfv.org/ci/view/dovetail/job/dovetail-docker-build-push-master/162/console
       Traceback: Running setup.py install for cryptography
                  c/_cffi_backend.c:15:17: fatal error: ffi.h: No such file or directory
    2. Refer to https://cryptography.io/en/latest/installation/
       For Debian and Ubuntu, the following command will ensure that the required
       dependencies are installed:
       sudo apt-get install build-essential libssl-dev libffi-dev python-dev
    
    Change-Id: Icb705823c58d8a557175d48b00745119c0a6b3b9
    Signed-off-by: xudan <xudan16@huawei.com>