Update git submodules
* Update docs/submodules/functest from branch 'stable/fraser'
  - Stop overriding neutron extension discovery
    
    Tempest is able to discover Trunk extensions [1].
    Then it's useless to override tempest.conf for Neutron trunk testing.
    
    [1] http://artifacts.opnfv.org/logs/functest/huawei-pod2/fraser/2018-07-26_12-11-20/tempest/tempest.log
    
    Change-Id: Ie5f90d5b15b5535526db01b3f08ec55d3ab1e0c0
    Signed-off-by: Cédric Ollivier <cedric.ollivier@orange.com>
    
  - Stop redirecting output to json files
    
    Rally may print additional data to console which results in an
    invalid json files. The json files are generated via rally instead of
    dumping stdout.
    
    It's mandatory to backport the next bugfix [1] in stable/fraser.
    
    [1] https://gerrit.opnfv.org/gerrit/#/c/60265/
    
    Change-Id: Ifbd90e685a7b52c70b3110a46e3c7991eddc05f4
    Signed-off-by: Cédric Ollivier <cedric.ollivier@orange.com>
    (cherry picked from commit 18c96abe8b6a3d6e919ff7ba64952454830357b3)
    
  - Refactor task results manipulation in rally
    
    Use data provided by report generation since the output of task
    results is not available as valid JSON if task didn't finish
    gracefully.
    
    JIRA: FUNCTEST-966
    
    Change-Id: Ieb906bc209cc26055babd5f4e6b2bb556724f9a8
    Signed-off-by: Juha Kosonen <juha.kosonen@nokia.com>
    (cherry picked from commit a4ed4eb2b6802bcf10aa944854a68b16147245cc)
    
  - Set filename_alt in tempest
    
    Change-Id: I9137ee30bd2107ec23ef6cfea92ccfc5f010410d
    Signed-off-by: Cédric Ollivier <cedric.ollivier@orange.com>
    (cherry picked from commit 29bd4108c51180a4d74443f676fc72866af6f1f6)
    
  - Allow overriding the default role
    
    It allows testing controllers which implements other RBAC policies.
    Defining NEW_USER_ROLE=admin will easily raise side effects for
    orchestrators such as Juju and Cloudify.
    
    Change-Id: Ia78a25381aeb8aa81fd1872661629e1c08432b8f
    Signed-off-by: Cédric Ollivier <cedric.ollivier@orange.com>
    (cherry picked from commit 51f3e7a3cc4409fb9dda03bffa1252a8660f38b0)
    
  - Typo
    
    Change-Id: Ibff3b01c50bfee266d0b99fab5b7baf271d43de4
    Signed-off-by: Cédric Ollivier <cedric.ollivier@orange.com>
    (cherry picked from commit 59fa6d205d03464246442a362cbed3caa8e32a2a)
    
  - Leverage cloudify_ims on Cloudify
    
    It also defines 2 new methods to avoid duplicating code:
      - TenantNetwork1.get_public_auth_url()
      - VmReady1.publish_image_alt()
    
    Shaker and Tempest are updated as well.
    
    Change-Id: Ie9095c57c580b95f067d5a8275ad71818b4df335
    Signed-off-by: Cédric Ollivier <cedric.ollivier@orange.com>
    (cherry picked from commit 8e96ddfb6a6548a9a7a9b4a686e01378425a1cd8)
    
  - Support py3 in uncovered packages
    
    It has to be noted that cloudify_rest_client doesn't support py3 then
    next unit tests vs cloudify-based testcases would be excluded.
    
    Change-Id: I0b0e64929d1238665c778ce51fd6abd5ccf06b6c
    Signed-off-by: Cédric Ollivier <cedric.ollivier@orange.com>
    (cherry picked from commit 7f2d7515e068c2ba072d4f3b4cf0997e06ae8460)
    
  - Add py3 support in tempest and rally
    
    Change-Id: I009d38a0db409ab4ec641cba9173ab2386d0ce2a
    Signed-off-by: Cédric Ollivier <cedric.ollivier@orange.com>
    (cherry picked from commit 09d6e6feef33fa47bca440a096894b851b1ebca5)
    
  - Remove cloudify_ims_perf
    
    All that modules are uncovered, unverified and deprecated.
    They will be safely reverted as soon as they are updated, verified by
    gates and unit tests are added.
    
    Change-Id: Iac0893f9f0ccb485d91cd17305e744aff9bf9414
    Signed-off-by: Cédric Ollivier <cedric.ollivier@orange.com>
    (cherry picked from commit cd8edb720d2e72842c35e9d6271fc81e6717679d)
    
  - Force region to RegionOne if OS_REGION_NAME is unset
    
    tempest still selects the first one if unset [1].
    
    JIRA: FUNCTEST-990
    
    [1] https://docs.openstack.org/tempest/latest/sampleconf.html
    
    Change-Id: I238d47173c2c4aa1db694028e4d44b80b0e280f1
    Signed-off-by: Cédric Ollivier <ollivier.cedric@gmail.com>
    (cherry picked from commit 8b2f524f0f17f06bf1de02e0165230bad218132b)
    
  - Refactor tempest common
    
    It also renames two testcases and updates all docs because tests
    run in parallel in case of tempest smoke.
    
    To force one thread as before:
    run:
        module: 'functest.opnfv_tests.openstack.tempest.tempest'
        class: 'TempestCommon'
        args:
            mode: '^tempest\.(api|scenario).*\[.*\bsmoke\b.*\]$'
            option:
                - '--concurrency=1'
    
    JIRA: FUNCTEST-989
    
    Change-Id: I1348f5908400a5046be8edf983db4afa12e546c3
    Signed-off-by: Cédric Ollivier <cedric.ollivier@orange.com>
    (cherry picked from commit eb8f57466325f398c6b8b5f4d15005c71879a269)
    
  - Add helper to find string in console
    
    It allows checking when cloud-init is finished (see heat_ims).
    
    Change-Id: I951aabff29457d7b7544a809f9fce1f83706035e
    Signed-off-by: Cédric Ollivier <cedric.ollivier@orange.com>
    (cherry picked from commit a80ebe8794dd2693203ceea65a13a69dcf508f94)
    
  - Minor change about subnet pool
    
    It reverts the subnet pool to 192.168.120.0/24.
    It avoids conflicts with default CPE private subnets.
    
    It also increases cloudify spawning timeout.
    
    Change-Id: I70183cede0690c2cbc74f9c30a38892d829db2c9
    Signed-off-by: Cédric Ollivier <cedric.ollivier@orange.com>
    (cherry picked from commit cb7e4e1e0687b79a0528ebe6a37683049d960210)
    
  - Increase timeout when creating servers
    
    It takes times to prepare disk on compute nodes (spawning).
    The default value is enough for all cirros VMs but it has to be
    increased for all cloudify VMs (4.1G).
    
    Change-Id: I3f1fc0142a73c586e9219a2718bfc467cc48e275
    Signed-off-by: Cédric Ollivier <cedric.ollivier@orange.com>
    (cherry picked from commit c391f57e6797e544d14285ca433b2499ed84cd5f)
    
  - Reduce cloudify manager disk size
    
    40 Gb is enough
    
    Change-Id: Iae6a72fcf91fda67bbd036f478e344478d48264f
    Signed-off-by: Valentin Boucher <valentin.boucher@kontron.com>
    (cherry picked from commit 363060485f107bb0af09977e101abc54f1fa207c)
    
  - Add secrets operations in cloudify.py
    
    It tries to prevent race conditions when running cloudify_ims.
    
    Traceback (most recent call last):
      File "/usr/lib/python2.7/site-packages/functest/core/singlevm.py", line 411, in run
        if not self.execute():
      File "/usr/lib/python2.7/site-packages/functest/opnfv_tests/vnf/ims/cloudify_ims.py", line 120, in execute
        self.cfy_client.secrets.create(k, val)
      File "/usr/lib/python2.7/site-packages/cloudify_rest_client/secrets.py", line 86, in create
        response = self.api.put('/secrets/{0}'.format(key), data=data)
      File "/usr/lib/python2.7/site-packages/cloudify_rest_client/client.py", line 263, in put
        timeout=timeout)
      File "/usr/lib/python2.7/site-packages/cloudify_rest_client/client.py", line 233, in do_request
        'SSL, but the client does'.format(e)
    ConnectionError: ('Connection aborted.', BadStatusLine("''",))
    
    Change-Id: Id2603bbda462b50d3140b6f45894c8810d542e4c
    Signed-off-by: Cédric Ollivier <cedric.ollivier@orange.com>
    (cherry picked from commit f426c72f2bb6381c631794a4b9f4c3322832e0d3)
    
  - Force a GET operations on cloudify API
    
    Cloudify is considered as running by the client but sometimes it
    failed when listing secrets right after. It adds that check in
    cloudify.py.
    
    Traceback (most recent call last):
      File "/usr/lib/python2.7/site-packages/functest/core/singlevm.py", line 391, in run
        if not self.execute():
      File "/usr/lib/python2.7/site-packages/functest/opnfv_tests/vnf/ims/cloudify_ims.py", line 119, in execute
        secrets_list = self.cfy_client.secrets.list()
      File "/usr/lib/python2.7/site-packages/cloudify_rest_client/secrets.py", line 113, in list
        response = self.api.get('/secrets', params=params)
      File "/usr/lib/python2.7/site-packages/cloudify_rest_client/client.py", line 252, in get
        timeout=timeout)
      File "/usr/lib/python2.7/site-packages/cloudify_rest_client/client.py", line 233, in do_request
        'SSL, but the client does'.format(e)
    ConnectionError: ('Connection aborted.', BadStatusLine("''",))
    
    Change-Id: Ie1b25ff529cfbf9f7476821499da369a46126e81
    Signed-off-by: Cédric Ollivier <cedric.ollivier@orange.com>
    (cherry picked from commit c4c3a33b9e6ae87c15331bf95e5544f0f680e4f0)
    
  - Publish cloudify scenario
    
    It eases deploying any vnf via Cloudify.
    It also stops duplicating code between vims and vrouter.
    
    Co-Authored-By: Valentin Boucher <valentin.boucher@kontron.com>
    
    Change-Id: I5fe06d91804f4781f6b1301da12862bac793ffbb
    Signed-off-by: Cédric Ollivier <ollivier.cedric@gmail.com>
    (cherry picked from commit 4c32f394e4ca9058ca69571754ff15156149251d)
    
  - Set swift_operator_role if required
    
    Apex creates member as default role which conflicts with the default
    swift_operator_role [1]. It detects the default role in lowercase as
    well and write it in rally.conf if required.
    
    [1] https://build.opnfv.org/ci/view/functest/job/functest-apex-virtual-suite-master/116/console
    
    Change-Id: Ic4dc98c793207fc32ff35852472742c92db6699c
    Signed-off-by: Cédric Ollivier <cedric.ollivier@orange.com>
    (cherry picked from commit bafbd217c68c70ae66e052833c3e33298b35da0c)