Update git submodules
* Update docs/submodules/fuel from branch 'stable/euphrates'
  - Merge "[baremetal] Retry cinder.controller on failure" into stable/euphrates
  - [baremetal] Retry cinder.controller on failure
    
    Occasionally, cinderng.volume_type_present errors with:
    ClientException: Service Unavailable (HTTP 503)
    Instead of retrying the whole state file, use `wait_for` macro
    to retry only this high state up to 5 times.
    
    Change-Id: Ib9ef017aca737e53c853007c13107d56d856c016
    Signed-off-by: Alexandru Avadanii <Alexandru.Avadanii@enea.com>
    (cherry picked from commit 92fb2b5e303b5e097a21d43612d5c8132f23152b)