Update git submodules
* Update docs/submodules/yardstick from branch 'master'
  - Merge "ping: don't split if target_vm is a dict"
  - ping: don't split if target_vm is a dict
    
    If we run sample/ping-hot.yaml, it will encounter an AttributeError, log
    see below:
    Traceback (most recent call last):
    File
    "/usr/local/lib/python2.7/dist-packages/yardstick/benchmark/runners/duration.py",
    line 69, in _worker_process
    method(data)
    File
    "/usr/local/lib/python2.7/dist-packages/yardstick/benchmark/scenarios/networking/ping.py",
    line 94, in run
    target_vm_name = target_vm.split('.')[0]
    AttributeError: 'dict' object has no attribute 'split'
    Because here host and target will be a dict
    
    JIRA: YARDSTICK-561
    
    Change-Id: I4b7628bf20050d6d516a80efe3785f750d27c05e
    Signed-off-by: Ross Brattain <ross.b.brattain@intel.com>