Update git submodules
* Update docs/submodules/yardstick from branch 'master'
  - Merge "Bugfix: kubernetes context do not implement _get_network"
  - Bugfix: kubernetes context do not implement _get_network
    
    Since kubernetes context do not implement _get_network,
    so when run unit test case, we will get a error:
    
        TypeError: Can't instantiate abstract class KubernetesContext with
        abstract methods _get_network
    
    Change-Id: Ib56abe7c580ef8a6fc9f52f3fcd566d0fa70e1cc
    Signed-off-by: chenjiankun <chenjiankun1@huawei.com>