Update git submodules
* Update docs/submodules/yardstick from branch 'stable/fraser'
  - Merge "Bump oslo.messaging version to 5.36.0" into stable/fraser
  - Bump oslo.messaging version to 5.36.0
    
    A decoding error was introduced in the AMQP libraries installed by
    oslo.messaging version 5.30.2.
    
    Error example:
    
    File "/home/jenkins/opnfv/slave_root/workspace/yardstick-verify-master/
            .tox/functional/local/lib/python2.7/site-packages/amqp/utils.py",
             line 89, in str_to_bytes
      return s.encode('utf-8')
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xd2 in position 3: ordinal not in range(128)
    
    This problem is fixed in the library versions installed in version 5.36.0.
    
    JIRA: YARDSTICK-1204
    
    Change-Id: I4719d8e0a0891ebbb3b87c31d593d15f897ef53a
    Signed-off-by: Rodolfo Alonso Hernandez <rodolfo.alonso.hernandez@intel.com>
    (cherry-picked from commit bcc841699c8072a74378774593729931e81b4398)