Update git submodules
* Update docs/submodules/snaps from branch 'master'
  - Closing keystone sessions after done with them.
    
    By not closing all of the keystone sessions being created when
    running all of the tests, this may be the root cause to the IOError
    occasionally being observed:
    
    IOError: [Errno 24] Too many open files
    
    JIRA: SNAPS-285
    
    Change-Id: I7fc7ab0c6cdd02f1ae32bb3ae4f121cb465d5693
    Signed-off-by: spisarski <s.pisarski@cablelabs.com>