Update git submodules
* Update docs/submodules/yardstick from branch 'master'
  - Merge "Heatstack create: fix str/bytes error in NamedTemporaryFile.write()"
  - Heatstack create: fix str/bytes error in NamedTemporaryFile.write()
    
    we need to use jsonutils.dump_as_bytes for NamedTemporaryFile.write()
    
    2018-02-11 19:15:01,366 [INFO] yardstick.orchestrator.heat heat.py:563 Creating stack 'yardstick-4359f33e' START
    2018-02-11 19:15:01,935 [ERROR] yardstick.benchmark.contexts.heat heat.py:317 stack failed
    Traceback (most recent call last):
      File "/home/rbbratta/yardstick-upstream/yardstick/yardstick/benchmark/contexts/heat.py", line 313, in deploy
        timeout=self.heat_timeout)
      File "/home/rbbratta/yardstick-upstream/yardstick/yardstick/orchestrator/heat.py", line 567, in create
        stack.create(self._template, self.heat_parameters, block, timeout)
      File "/home/rbbratta/yardstick-upstream/yardstick/yardstick/orchestrator/heat.py", line 56, in create
        template_file.write(jsonutils.dumps(template))
      File "/home/rbbratta/yardstick_venv3/lib/python3.5/tempfile.py", line 622, in func_wrapper
        return func(*args, **kwargs)
    TypeError: a bytes-like object is required, not 'str'
    
    JIRA: YARDSTICK-1005
    Change-Id: I504f23b86119b62f3aea5b83a445b97bf810220c
    Signed-off-by: Ross Brattain <ross.b.brattain@intel.com>