Update git submodules
* Update docs/submodules/yardstick from branch 'stable/danube'
  - Merge "Add NUMA pinning support for node context" into stable/danube
  - Update yardstick framework architecture in userguide
    
    JIRA: YARDSTICK-590
    
    This patch update the yardstick framework architecture in the userguide,
    also fix some rst grammar mistakes
    
    Change-Id: I84e7c24b4cd936a01f4c191e9f530f15f9f711de
    Signed-off-by: JingLu5 <lvjing5@huawei.com>
    (cherry picked from commit 7150e6bc49098937edcac0fa9fa108329c74af4a)
    
  - Bugfix: Could not load EntryPoint.parse when using 'openstack -h'
    
    JIRA: YARDSTICK-599
    
    Python-openstackclient 3.7.0 has a issus that cause -help info can not be
    loaded properly when executing 'openstack -h' command.
    
    Change-Id: I0a5f7a0943d56764b1c4d5d7335aa67b30f39b4c
    Signed-off-by: JingLu5 <lvjing5@huawei.com>
    (cherry picked from commit ff3501f28a80537cb9a2453708e2d3d62c4a3292)
    
  - Merge "Bugfix: TC002 image error in fuel-arm pod scenarios" into stable/danube
  - Bugfix: TC002 image error in fuel-arm pod scenarios
    
    JIRA: YARDSTICK-601
    
    This error is cause because the TC 002 configuration file has been modified in
    image section, the old sed command in load_images.sh
    "sed -i 's/image: cirros-0.3.3/image: TestVM/g' tests/opnfv/test_cases/opnfv_yardstick_tc002.yaml samples/ping.yaml" didn't work properly.
    
    Change-Id: Ie897213622d05bb267f94b466eb2529e797d484e
    Signed-off-by: JingLu5 <lvjing5@huawei.com>
    (cherry picked from commit 2fb078e21a3cd0dc69732f33b5a6ecc422eb577d)
    
  - aarch64: Improve arch detection snippet
    
    Get the arch from a compute node
    Also move code that depends on YARD_IMG_ARCH,
    after YARD_IMG_ARCH gets set
    
    JIRA: YARDSTICK-591
    
    Change-Id: I5ed3ef9cfa92e5bf9e6ada21396d18643cf1a55c
    Signed-off-by: Matei Valeanu <Matei.Valeanu@enea.com>
    (cherry picked from commit 13d68ab65475ec556383480a17dbaf63e3ab140c)
    
  - Bugfix: load_images cleanup, shellcheck fixes
    
    We should have run shellcheck on this.
    
    This is why we don't use the shell, too many
    obscure gotchas.
    
    shellcheck: load_images.sh:25:75: warning: sudo doesn't affect redirects. Use .. | sudo tee -a file [SC2024]
    
      sudo echo foo >> /etc/foo won't work,
    
    the >> will be run in the current shell,
    replace with:
    
      echo foo | sudo tee -a /etc/foo
    
    shellcheck: load_images.sh:47:15: warning: Declare and assign separately to avoid masking return values. [SC2155]
    
    replace local cmd='a' with two line version
    
    shellcheck: load_images.sh:141:32: error: [ .. ] can't match globs. Use [[ .. ]] or grep. [SC2081]
    
    use [[ ]]
    
    Change-Id: I14d9768612ea147eaf139603f7eb8753e979ba2c
    Signed-off-by: Ross Brattain <ross.b.brattain@intel.com>
    (cherry picked from commit 892d2e536e46a6e6427c061931c58f80b542589d)
    
  - Bugfix: remove vivid as it is EOL
    
    Vivid is end of life, and thus not supported.
    
    Change-Id: Ia293fcd6fd2a3279a642a6dbbb7ad1811334c3e1
    Signed-off-by: Ross Brattain <ross.b.brattain@intel.com>
    (cherry picked from commit 14172bb39e8e30f37ec5bb80be6b187ab6858e88)
    
  - ubuntu-server-cloudimg-modify.sh: shellcheck fixes
    
    fixes for shellcheck warning
    
    ubuntu-server-cloudimg-modify.sh:51:23: warning: Quote this to prevent word splitting. [SC2046]
    ubuntu-server-cloudimg-modify.sh:51:30: note: Double quote to prevent globbing and word splitting. [SC2086]
    
    Change-Id: I6cff0713a0471e5ce94211d42a7c8b45e3761c4d
    Signed-off-by: Ross Brattain <ross.b.brattain@intel.com>
    (cherry picked from commit 8a2b7cdb29ff6a56d06e8f83fc098def40e1ed51)
    
  - Merge "aarch64: Fix missing qemu-aarch64-static in chroot" into stable/danube
  - aarch64: Fix missing qemu-aarch64-static in chroot
    
    During recent rework, we lost the explicit copy of qemu-aarch64-static
    from docker to chroot; so when trying to execute AArch64 binaries
    inside chroot, no emulator was present to handle it.
    
    This change brings back (inside chroot) the missing emulator binary.
    
    JIRA: YARDSTICK-595
    
    Change-Id: I146e2eeec2e9452a0db36f0bf0a466a8affc2005
    Signed-off-by: Paul Vaduva <Paul.Vaduva@enea.com>
    (cherry picked from commit 742ee6f3249a6204a351fe02c1334c9b14213e51)
    
  - Refine test case description for tc076
    
    JIRA: YARDSTICK-594
    
    Change-Id: Ieaf13a875d00c279d4da57dcdba5bcfb09f44e8f
    Signed-off-by: JingLu5 <lvjing5@huawei.com>
    (cherry picked from commit f83a3a15d16333c422ba15b745e94d64712d73bb)
    
  - Dockerfile: Use qemu-user-static from xenial 
    
    qemu-user-static from Trusty crashes when ssl is used in chroot.
    
    JIRA: YARDSTICK-592
    
    Change-Id: I81e8f04d7469082ceb6512cb09e11dfa672e5e98
    Signed-off-by: Paul Vaduva <Paul.Vaduva@enea.com>
    (cherry picked from commit 9d9925c30e9c7ad477041c28251b411432457568)
    
  - update lxd image disk format for openstack CLI
    
    JIRA: YARDSTICK-598
    
    As we have replaced 'glance image-create' command with 'openstack image create'
    command, we also need to update the disk-format for openstack CLI. the
    'root-tar' is no longer a valid choice. (choose from 'ami', 'ari', 'aki',
    'vhd', 'vmdk', 'raw', 'qcow2', 'vhdx', 'vdi', 'iso', 'ploop')
    
    Change-Id: I53f839f658c5a6f216f5bb942b1c4f4dcdbf9814
    Signed-off-by: JingLu5 <lvjing5@huawei.com>
    (cherry picked from commit d64fbf2f276a98a7cc37d92c57f5b7f3517286b8)
    
  - Merge "Bugfix: replace MD5SUM with SHA256SUMs" into stable/danube
  - Merge "add missing test suite files for new scenarios" into stable/danube
  - Bugfix: replace MD5SUM with SHA256SUMs
    
    MD5 is broken and should not be used
    
    Change-Id: Ib168932387f58f0a538d865f8ef4e3cda046a35a
    Signed-off-by: Ross Brattain <ross.b.brattain@intel.com>
    (cherry picked from commit fe655f15b0838b41c8c91543898ceebf23f1494c)
    
  - Bugfix: netperf_bottleneck execute failed because is_same_heat_context return True
    
    JIRA: YARDSTICK-600
    
    Bugfix: netperf_bottleneck execute failed because is_same_heat_context return True
    So it exit without warning.
    I will remove the 'return True' from it.
    
    Change-Id: I48d62bd15ec359e2121f236c48d9d349174f2c10
    Signed-off-by: chenjiankun <chenjiankun1@huawei.com>
    
  - add missing test suite files for new scenarios
    
    JIRA: YARDSTICK-589
    
    Change-Id: I1690d4e2bd741fe1514c8496ee6ff10b72158859
    Signed-off-by: JingLu5 <lvjing5@huawei.com>
    (cherry picked from commit f7371c36ff26ae9a8f526d0b76d13020a2239a23)
    
  - Add NUMA pinning support for node context
    
    JIRA: YARDSTICK-574
    
    Since the yardstick framework now has supported an improved node type context,
    this patch adds support for VM NUMA pinning ability in the node type context.
    It provides several scripts that can be used to configurate the controller and
    compute nodes
    
    Change-Id: If5eafdca6df1b1196bc17bfdd12aea9f4016752f
    Signed-off-by: JingLu5 <lvjing5@huawei.com>
    (cherry picked from commit be4fad1e486f6c4bf993335f0aecaa3682a37da8)
    
  - add missing test suite files for new scenarios
    
    JIRA: YARDSTICK-589
    
    Some new scenarios, e.g, opnfv_k8-nosdn-nofeature-noha_daily, have been added
    in the Danube release, test suite files for these scenarios should be added.
    
    Change-Id: If3f4ef233b7b1516e182ed28f15feece1728e6d9
    Signed-off-by: JingLu5 <lvjing5@huawei.com>
    (cherry picked from commit 94d0c6200c8f39988911eedffea703f8b4737fcf)
    
  - Bugfix: yardstick-image built without test tools
    
    JIRA: YARDSTICK-593
    
    The yardstick-image now built dosen't have test tools in it.
    This patch aims to fix this issus.
    
    Change-Id: I9863a933106236835c16e21f84aa107ffd554df7
    Signed-off-by: JingLu5 <lvjing5@huawei.com>
    (cherry picked from commit bd90c394fe223c5d465d70fb24076ef1d9258c91)
    
  - Merge "Bugfix: network_utilization: parse error" into stable/danube
  - fix fuel plugin installation issue
    
    Change-Id: Ie17ba0ac941d1b96148ee23ed9522a93309f56c5
    Signed-off-by: Guo Ruijing <ruijing.guo@intel.com>
    
  - Bugfix: fatal: destination path '/opt/tempT' already exists and is not an empty directory.
    
    JIRA: YARDSTICK-588
    
    ubuntu-server-cloudimg-modify.sh: fixes and cleanup
    https://build.opnfv.org/ci/view/fuel/job/yardstick-fuel-virtual-daily-master/1233/console
    saw this in an error log, not sure if it is a real error
    + [[ amd64 = \a\r\m\6\4 ]]
    + git clone https://github.com/kdlucas/byte-unixbench.git /opt/tempT
    fatal: destination path '/opt/tempT' already exists and is not an empty
    directory.
    + error_trap
    + local rc=128
    + set +e
    + '[' -z '' ']'
    + exitcode=128
    workaround by deletign /opt/tempT always before cloning
    also improve ln with relative symlink and forcing filename target
    
    Change-Id: Ia9c35a877207494623055b1b2134f7834fadedf8
    Signed-off-by: chenjiankun <chenjiankun1@huawei.com>
    (cherry picked from commit f31b7d56c07c17607df605aacc9b60bf786428e0)
    
  - Bugfix: network_utilization: parse error
    
    JIRA: YARDSTICK-586
    
    When run tc072, there is a bug: network_utilization: parse error, see the log:
    ERROR ('network_utilization: parse error', [], [u'05:10:46', u'IFACE',
            u'rxpck/s', u'txpck/s', u'rxkB/s', u'txkB/s', u'rxcmp/s',
            u'txcmp/s', u'rxmcst/s', u'%ifutil'])
    Traceback (most recent call last):
        File
        "/usr/local/lib/python2.7/dist-packages/yardstick/benchmark/runners/duration.py",
        line 69, in _worker_process
        method(data)
        File
        "/usr/local/lib/python2.7/dist-packages/yardstick/benchmark/scenarios/networking/netutilization.py",
        line 191, in run
        result.update(self._get_network_utilization())
        File
        "/usr/local/lib/python2.7/dist-packages/yardstick/benchmark/scenarios/networking/netutilization.py",
        line 182, in _get_network_utilization
        result = self._filtrate_result(raw_result)
        File
        "/usr/local/lib/python2.7/dist-packages/yardstick/benchmark/scenarios/networking/netutilization.py",
        line 146, in _filtrate_result
        fields, line)
        RuntimeError: ('network_utilization: parse error', [], [u'05:10:46',
                u'IFACE', u'rxpck/s', u'txpck/s', u'rxkB/s', u'txkB/s',
                u'rxcmp/s', u'txcmp/s', u'rxmcst/s', u'%ifutil'])
    
    Maybe the tool has some changes.
    
    Change-Id: I6c4fe3fe9f749ec942fb5fbd799b8f4ab9a5c16c
    Signed-off-by: chenjiankun <chenjiankun1@huawei.com>
    
  - Bugfix: yardstick https support
    
    JIRA: YARDSTICK-587
    
    When run in https environment, there is a bug:
    error: failed to deploy stack: '_init_() got an unexpected keyword argument 'ca_cert''
    The reason is the key pass to Session() is cacert, but the key should be
    verify.
    
    Change-Id: Ia9fc1d7908c2fca9d827a5f64deac7cd333d5c07
    Signed-off-by: chenjiankun <chenjiankun1@huawei.com>
    (cherry picked from commit 747e3c5f8a882b07b6876aae61c84d05a8b832f4)