Update git submodules
* Update docs/submodules/yardstick from branch 'stable/danube'
  - Bugfix: Error validating value 'cirros-0.3.5'
    
    JIRA: YARDSTICK-607
    
    some scenarios come with a Cirros-0.3.5 image, Yardstick's load_images.sh will
    load a second cirros-0.3.5 image, causing the following error:
    2017-03-27 07:42:58,317 yardstick.orchestrator.heat heat.py:449 INFO Creating stack 'demo-2ada98f3'
    error: failed to deploy stack: 'ERROR: Property error: : resources.ares.demo-2ada98f3.properties.image: : Error validating value 'cirros-0.3.5': No images unique match found for
    {'name': u'cirros-0.3.5'}
    
    This patch fixs this error by skipping load cirros image if there already exist
    one in the glance.
    
    Change-Id: I4d43d82d331f6575efd4560be9b6be175e03cd1b
    Signed-off-by: JingLu5 <lvjing5@huawei.com>
    (cherry picked from commit 3f70095d15afb86567f885cbfbd89183d857f671)